
###

POST http://localhost:3000/auth/google
Content-Type: application/json
{
  "credential": "eyJhbGciOiJSUzI1NiIsImtpZCI6Ijg1ZTU1MTA3NDY2YjdlMj…NMcxQ2mFSXj2BMhtGfzQ-tdIbG1e2zw1iR4OKMuR6p_VbBq_w"
}


###

POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "name": "testUser",
  "email": "test@test.com",
  "password": "test123",
  "roles": "owner"
}

###

POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "name": "shani",
  "email": "shani@test.com",
  "password": "12345",
  "roles": "owner"
}

###

POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "name": "shani",
  "email": "shani@test.com",
  "password": "12345"
}

###

POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "name": "testUser",
  "email": "test@test.com",
  "password": "test123"
}

###

POST http://localhost:3000/auth/logout
Content-Type: application/json

{
  "token": "auth_token_here"
}

###
GET http://localhost:3000/user/
authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTkyYjE3ZWYyYzFlMWQxYTcwYTQwODMiLCJpYXQiOjE3MDQxMTI1MTB9.KyfBMHGe1yB9MpB74D8ry-nammjJJ1dgKL9TRILkew4
###
GET http://localhost:3000/user/test@test.com
authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTkyYjE3ZWYyYzFlMWQxYTcwYTQwODMiLCJpYXQiOjE3MDQxMTI1MTB9.KyfBMHGe1yB9MpB74D8ry-nammjJJ1dgKL9TRILkew4


###
GET http://localhost:3000/user/id/6592b17ef2c1e1d1a70a407e
authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTkyYjE3ZWYyYzFlMWQxYTcwYTQwN2UiLCJpYXQiOjE3MDQxMTI1MTB9.2v21FY73BHh--_ouKTwnVE_1da_N8SGJ8vUNpMVmPSM
###
PATCH http://localhost:3000/user/update
authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTkyODU3YzYzNDEyMjdmOTBlM2ZkZDgiLCJpYXQiOjE3MDQxMDEyNDR9.TEnFYNnvbzgw96hcumzSttxQcWBFNM1lPQUFGDkV8v0
Content-Type: application/json

{
  "id": "6592857c6341227f90e3fdd3",
  "user": {
    "name": "Shani Yaish",
    "email": "update@example.com",
    "password": "55555"
  }
}



###
DELETE http://localhost:3000/user/delete/659297dde267a89fbb7a52ec
authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTkyOTdlZTVjZTA5NDRhMjU3Y2Q0NDIiLCJpYXQiOjE3MDQxMDU5NzF9.wcSn8bBsnC4xlLIChSxf0QttvfQcCSHfYXSdrj7agTw

###
PATCH http://localhost:3000/user/updateOwnProfile
authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTkyYzQ3NzdlNjZkZTcyMDEyYmYzODQiLCJpYXQiOjE3MDQxMTczNjd9.6IVv6HL9B39inVpQfscDJlz73sYVzf2RKm3xgFJv1uQ
Content-Type: application/json

{
  "id": "6592c4777e66de72012bf37f",
  "user": {
    "name": "Shani Yaish",
    "email": "update@gmail.com",
    "password": "8888"
  }
}
